# Site settings
title: "Base A.I - Whitepaper"
description: "Infraestrutura de IA como Ativo Real - Democratizando o acesso financeiro à infraestrutura de Inteligência Artificial"
baseurl: ""
url: ""

# Build settings
markdown: kramdown
highlighter: rouge

# Exclude from processing
exclude:
  - README.md
  - SETUP_INSTRUCTIONS.md

# Site metadata
author: "Base A.I"
email: "contato@baseai.com.br"
company: "Base A.I"
